services:
  - type: web
    name: movie-rewind
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TMDB_API_KEY
        sync: false
